### PR TITLE
[#189] Add OSX check on CI

### LINKED ISSUE #189: Add OSX check on CI

### PR DESCRIPTION
**Pull request by chshersh**
Resolves #189

### CODE REVIEW

**Review by vrom911 — APPROVED** [review]
Looks great 👍🏼

**Comment by chshersh** [comment]
Just added `chronos` as a GitHub dependency from my fork to see how well CI works. Should be removed once `chronos` is released to Hackage 💎

**Comment by vrom911** [comment]
Nice! Should we wait or merge as it is now?

**Comment by chshersh** [comment]
@vrom911 We can merge now (as the PR fixes CI substantially) and open a separate PR for removing GitHub dependency after the new `chronos` release:

* https://github.com/andrewthad/chronos/pull/71

**Comment by NicolasT** [comment]
Looks like https://github.com/chshersh/chronos no longer exists (or not publicly, at least), and ref d16494c1df61023dab63d41d276c55f233ef887e doesn't exist in https://github.com/andrewthad/chronos, hence given the `cabal.project` file in this repository a simple `cabal build` fails.

**Pull request merged**
