### PR TITLE
tutorials: add demo for LoggerT and SimpleMsg, #84

### PR DESCRIPTION
**Pull request by xieyuschen**
I'm going to add all tutorials under #84. 

As I'm not a senior person to Haskell, please correct me if I make any mistake.

Regard

### CODE REVIEW

**Comment by xieyuschen** [comment]
Hi @vrom911 , could you kindly to review the PR about tutorials?

**Comment by alaendle** [comment]
Without having a detailed look, anything is better than nothing; so please merge directly - if there is still a need for improvement, this can also be done later.

**Comment by xieyuschen** [comment]
Hi @alaendle @vrom911 , could you kindly help to review this PR? If there are some places to be fixed, I'm glad to improve it in the PR also.

**Comment by alaendle** [comment]
@xieyuschen (fyi @vrom911) - Unfortunately there is nothing I can do; I have not the necessary rights/permissions to push things forward (guess I have to be added to the code owner files to be able to do reviews/merges).

**Comment by vrom911** [comment]
Appologies!
@alaendle I remove the code owners permission, you could add yourself later as well, it would be great too!

@xieyuschen thanks a lot for your contributions! ❤️

**Review by alaendle — APPROVED** [review]

**Comment by alaendle** [comment]
@vrom911 Thank you for your trust 😄 Still I see... 
grafik

**Comment by vrom911** [comment]
Sorry, @alaendle , still figuring it out! Can you try now? I gave you admin permissions now :)

**Comment by alaendle** [comment]
Thanks - now I would be able to merge - but this is up to your review: 
grafik

**Comment by alaendle** [comment]
@vrom911 - Btw, could you also give me these permissions on the other repos of the org? 😉

**Comment by vrom911** [comment]
@alaendle Should have all the accesses and righys to all repos in the org, thanks a lot for helping with this ❤️

**Comment by alaendle** [comment]
@vrom911 Many thanks! 👏

**Comment by xieyuschen** [comment]
> Thanks - now I would be able to merge - but this is up to your review: grafik

oops, the PR is pending for your @vrom911 review.

**Comment by vrom911** [comment]
@alaendle I think one review is fine for the PR, so feel free to merge PRs that you approved even if I didn't get to review that yet (especially if it takes too much time) 👌🏼

**Pull request merged**
